manage version at the top level

diff --git a/cli/go/src/pxf-cli/Makefile b/cli/go/src/pxf-cli/Makefile
--- a/cli/go/src/pxf-cli/Makefile
+++ b/cli/go/src/pxf-cli/Makefile
@@ -1,3 +1,5 @@
+include ../../../../common.mk
+
 .PHONY: all depend build stage install test clean help
 .DEFAULT_GOAL := build
 
@@ -5,7 +7,7 @@ TARGET := $(shell echo $${PWD\#\#*/})
 PXF_ROOT_DIR := $(shell cd ../../../.. && pwd)
 PXF_SERVER_DIR := ${PXF_ROOT_DIR}/server
 PXF_CLI_DIR := ${PXF_ROOT_DIR}/cli
-PXF_VERSION := $(shell grep version= ${PXF_SERVER_DIR}/gradle.properties | cut -d= -f2)
+PXF_VERSION ?= $(shell $(PXF_ROOT_DIR)/version)
 
 LDFLAGS := -ldflags "-X ${TARGET}/cmd.version=${PXF_VERSION}"
 GO_DEP_CACHE := ${PXF_ROOT_DIR}/cli/go/pkg/dep
@@ -35,16 +37,16 @@ build: depend
 	go build -v ${LDFLAGS}
 	go install ${LDFLAGS}
 
-stage: build
+stage: test
 	mkdir -p ${PXF_CLI_DIR}/build/stage/pxf/bin
 	cp ${GOPATH}/bin/pxf-cli ${PXF_CLI_DIR}/build/stage/pxf/bin
 
 install: build
 	@if [ -z "$(PXF_HOME)" ]; then \
-		echo "ERROR: PXF_HOME is not set correctly"; exit 2; \
+		echo "ERROR: PXF_HOME is not set"; exit 2; \
 	fi
-	mkdir -p ${PXF_HOME}/bin
-	cp ${GOPATH}/bin/pxf-cli ${PXF_HOME}/bin
+	mkdir -p $(PXF_HOME)/bin
+	cp $(GOPATH)/bin/pxf-cli $(PXF_HOME)/bin
 
 test: build
 	ginkgo cmd end_to_end
